title: Angular Performance Checklist
description: Cheatsheet for developing ⚡lightning⚡ fast Angular applications.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
