title: Angular2 Performance Checklist
description: Cheatsheet for developing ⚡lightning⚡ fast Angular 2 applications.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
